### ISSUE TITLE
week1: problem

### ISSUE THREAD

**Issue by thangdnsf** [Truong1803/Probability-and-Statistics#1]
You are hard-working. You should take your time to complete the assignment at the end of week 1.
Stay safe!

**Comment by Truong1803** [comment]
Em thấy week 1 có mỗi phần Quiz là làm được còn các bài lab thì có sẵn hoặc submit trong lúc học rồi ạ

**Comment by thangdnsf** [comment]
submit đc thì capture điểm nhé

**Comment by thangdnsf** [comment]
có thể em nhầm lab với assignment đấy

**Comment by Truong1803** [comment]
week1 trong các video đều có 1 bài tập nhỏ làm xong submit luôn và bài Quiz cuối còn em không thấy có bài tập nào nữa

**Comment by thangdnsf** [comment]
ok, minh mới check lại đúng là tuần này ko có thật hi
